// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Yunho Cho

/// @file
/// Validates DC-group and AC-metadata logical tokenization.

#include "codestream/dc_group.h"

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <span>
#include <string_view>
#include <vector>

#include "codec/chroma_from_luma.h"
#include "codec/reconstruction.h"

namespace {

template <typename T>
gjxl::PlaneView<const T> View(const std::vector<T>& values,
                              gjxl::Extent2D extent) {
  return {values.data(), extent, extent.width};
}

gjxl::ConstImage3I32View DcView(
  const std::array<std::vector<int32_t>, 3>& planes, gjxl::Extent2D extent) {
  return gjxl::ConstImage3I32View{{
    View(planes[0], extent),
    View(planes[1], extent),
    View(planes[2], extent),
  }};
}

bool CheckTokens(std::string_view name,
                 std::span<const gjxl::EntropyToken> actual,
                 std::span<const gjxl::EntropyToken> expected) {
  if (!std::ranges::equal(actual, expected)) {
    std::cerr << name << " token fixture mismatch\n";
    return false;
  }
  return true;
}

bool CheckPinnedTinyFixture() {
  // Generated by jxl_tiny_trace at f60855353d1345efa361713ca8511a8d45fb5957
  // for the deterministic gradient_17x9_d1 fixture. The encoder's numerical
  // libjxl reference remains e8ff09762481785938d8e4e01333ed3917571161.
  constexpr gjxl::Extent2D kBlocks{3, 2};
  const std::array<std::vector<int32_t>, 3> dc{{
    {-16, 30, 49, -51, -16, 0},
    {320, 375, 394, 435, 467, 480},
    {27, 31, 22, -20, -11, -15},
  }};
  const std::array<gjxl::EntropyToken, 18> expected_dc{{
    {26, 640},
    {13, 110},
    {13, 38},
    {13, 230},
    {12, 64},
    {12, 26},
    {26, 31},
    {32, 92},
    {20, 38},
    {32, 69},
    {29, 21},
    {41, 5},
    {26, 54},
    {20, 8},
    {20, 17},
    {20, 93},
    {32, 10},
    {32, 7},
  }};

  std::vector<gjxl::EntropyToken> dc_tokens;
  gjxl::Status status =
    gjxl::TokenizeSimpleDcGroup(DcView(dc, kBlocks), &dc_tokens);
  if (!status.ok() || !CheckTokens("pinned DC", dc_tokens, expected_dc)) {
    std::cerr << "Pinned DC tokenization failed: " << status.message() << '\n';
    return false;
  }

  gjxl::AcStrategyGrid strategies;
  if (!gjxl::AcStrategyGrid::Create(kBlocks, &strategies).ok()
      || !strategies.Set(0, 0, gjxl::AcStrategyType::kDct8x16).ok()
      || !strategies.Set(2, 0, gjxl::AcStrategyType::kDct8).ok()
      || !strategies.Set(0, 1, gjxl::AcStrategyType::kDct8x16).ok()
      || !strategies.Set(2, 1, gjxl::AcStrategyType::kDct8).ok()) {
    return false;
  }
  const std::vector<int8_t> y_to_x = {-4};
  const std::vector<int8_t> y_to_b = {-44};
  const std::vector<int32_t> quant(6, 6);
  const std::vector<uint8_t> sharpness(6, 4);
  const std::array<gjxl::EntropyToken, 16> expected_metadata{{
    {2, 7},
    {1, 87},
    {10, 14},
    {8, 0},
    {10, 14},
    {8, 0},
    {4, 3},
    {5, 0},
    {5, 0},
    {5, 0},
    {0, 8},
    {0, 8},
    {0, 8},
    {0, 8},
    {0, 8},
    {0, 8},
  }};
  std::vector<gjxl::EntropyToken> metadata_tokens;
  size_t anchor_count = 0;
  status = gjxl::TokenizeSimpleAcMetadata(
    {
      .y_to_x_map = View(y_to_x, {1, 1}),
      .y_to_b_map = View(y_to_b, {1, 1}),
      .strategies = &strategies,
      .raw_quant_field = View(quant, kBlocks),
      .epf_sharpness = View(sharpness, kBlocks),
    },
    &metadata_tokens, &anchor_count);
  if (!status.ok() || anchor_count != 4
      || !CheckTokens("pinned AC metadata", metadata_tokens,
                      expected_metadata)) {
    std::cerr << "Pinned metadata tokenization failed: " << status.message()
              << '\n';
    return false;
  }
  return true;
}

bool CheckDcSignedExtremesAndAtomicOverflow() {
  constexpr gjxl::Extent2D kOne{1, 1};
  const std::array<std::vector<int32_t>, 3> extremes{{
    {std::numeric_limits<int32_t>::max()},
    {std::numeric_limits<int32_t>::min()},
    {0},
  }};
  const std::array<gjxl::EntropyToken, 3> expected{{
    {26, std::numeric_limits<uint32_t>::max()},
    {26, std::numeric_limits<uint32_t>::max() - 1},
    {26, 0},
  }};
  std::vector<gjxl::EntropyToken> tokens;
  gjxl::Status status =
    gjxl::TokenizeSimpleDcGroup(DcView(extremes, kOne), &tokens);
  if (!status.ok() || !CheckTokens("DC signed extremes", tokens, expected)) {
    return false;
  }

  constexpr gjxl::Extent2D kTwo{2, 1};
  const std::array<std::vector<int32_t>, 3> overflow{{
    {0, 0},
    {std::numeric_limits<int32_t>::min(), std::numeric_limits<int32_t>::max()},
    {0, 0},
  }};
  const std::vector<gjxl::EntropyToken> sentinel = {{99, 77}};
  tokens = sentinel;
  status = gjxl::TokenizeSimpleDcGroup(DcView(overflow, kTwo), &tokens);
  if (status.code() != gjxl::StatusCode::kInvalidArgument
      || tokens != sentinel) {
    std::cerr << "Overflowing DC residual changed its output\n";
    return false;
  }
  return true;
}

bool CheckAllStrategiesAndActualMetadata() {
  constexpr gjxl::Extent2D kBlocks{16, 4};
  gjxl::AcStrategyGrid strategies;
  if (!gjxl::AcStrategyGrid::Create(kBlocks, &strategies).ok()
      || !strategies.Set(0, 0, gjxl::AcStrategyType::kDct8).ok()
      || !strategies.Set(1, 0, gjxl::AcStrategyType::kDct16x16).ok()
      || !strategies.Set(3, 0, gjxl::AcStrategyType::kDct32x32).ok()
      || !strategies.Set(7, 0, gjxl::AcStrategyType::kDct16x8).ok()
      || !strategies.Set(8, 0, gjxl::AcStrategyType::kDct8x16).ok()
      || !strategies.Set(10, 0, gjxl::AcStrategyType::kDct32x16).ok()
      || !strategies.Set(12, 0, gjxl::AcStrategyType::kDct16x32).ok()) {
    return false;
  }
  strategies.fill_empty_dct8();

  const std::vector<int8_t> y_to_x = {-4, 3};
  const std::vector<int8_t> y_to_b = {7, -8};
  std::vector<int32_t> quant(kBlocks.width * kBlocks.height, 1);
  quant[1] = 256;
  std::vector<uint8_t> sharpness(kBlocks.width * kBlocks.height);
  for (size_t index = 0; index < sharpness.size(); ++index) {
    sharpness[index] = static_cast<uint8_t>(index % 8);
  }

  std::vector<gjxl::EntropyToken> tokens;
  size_t anchors = 0;
  const gjxl::Status status = gjxl::TokenizeSimpleAcMetadata(
    {
      .y_to_x_map = View(y_to_x, {2, 1}),
      .y_to_b_map = View(y_to_b, {2, 1}),
      .strategies = &strategies,
      .raw_quant_field = View(quant, kBlocks),
      .epf_sharpness = View(sharpness, kBlocks),
    },
    &tokens, &anchors);
  const std::array<gjxl::EntropyToken, 4> expected_cfl{{
    {2, 7},
    {2, 14},
    {1, 14},
    {1, 29},
  }};
  const std::array<gjxl::EntropyToken, 7> expected_strategies{{
    {10, 0},
    {10, 8},
    {9, 10},
    {9, 12},
    {8, 14},
    {8, 20},
    {8, 22},
  }};
  const std::array<gjxl::EntropyToken, 3> expected_quant{{
    {6, 0},
    {6, 510},
    {3, 509},
  }};
  const size_t quant_offset = expected_cfl.size() + anchors;
  const size_t sharpness_offset = expected_cfl.size() + 2 * anchors;
  if (!status.ok() || anchors < expected_strategies.size()
      || tokens.size() != sharpness_offset + sharpness.size()
      || !CheckTokens(
        "nonconstant CfL",
        std::span<const gjxl::EntropyToken>(tokens).first(expected_cfl.size()),
        expected_cfl)
      || !CheckTokens("seven strategies",
                      std::span<const gjxl::EntropyToken>(tokens).subspan(
                        expected_cfl.size(), expected_strategies.size()),
                      expected_strategies)
      || !CheckTokens("quant 1/256",
                      std::span<const gjxl::EntropyToken>(tokens).subspan(
                        quant_offset, expected_quant.size()),
                      expected_quant)) {
    std::cerr << "Synthetic AC metadata failed: " << status.message() << '\n';
    return false;
  }
  for (size_t index = 0; index < sharpness.size(); ++index) {
    if (tokens[sharpness_offset + index]
        != gjxl::EntropyToken{0, gjxl::PackSigned(sharpness[index])}) {
      std::cerr << "Actual EPF sharpness was not retained in token order\n";
      return false;
    }
  }
  return true;
}

gjxl::SimpleAcMetadataInput OneBlockMetadataInput(
  const gjxl::AcStrategyGrid* strategies, const std::vector<int8_t>& map,
  const std::vector<int32_t>& quant, const std::vector<uint8_t>& sharpness,
  size_t block_x = 0) {
  return {
    .y_to_x_map = View(map, {1, 1}),
    .y_to_b_map = View(map, {1, 1}),
    .strategies = strategies,
    .block_x = block_x,
    .raw_quant_field = View(quant, {1, 1}),
    .epf_sharpness = View(sharpness, {1, 1}),
  };
}

bool CheckMetadataRejectionsAreAtomic() {
  gjxl::AcStrategyGrid crossing;
  gjxl::AcStrategyGrid dct8;
  gjxl::AcStrategyGrid unsupported;
  if (!gjxl::AcStrategyGrid::Create({2, 1}, &crossing).ok()
      || !crossing.Set(0, 0, gjxl::AcStrategyType::kDct8x16).ok()
      || !gjxl::AcStrategyGrid::Create({1, 1}, &dct8).ok()
      || !dct8.Set(0, 0, gjxl::AcStrategyType::kDct8).ok()
      || !gjxl::AcStrategyGrid::Create({1, 1}, &unsupported).ok()
      || !unsupported.Set(0, 0, gjxl::AcStrategyType::kIdentity).ok()) {
    return false;
  }
  const std::vector<int8_t> map = {0};
  const std::vector<int32_t> quant = {1};
  const std::vector<uint8_t> sharpness = {4};
  const std::vector<gjxl::EntropyToken> sentinel = {{77, 99}};
  std::vector<gjxl::EntropyToken> tokens = sentinel;
  size_t anchors = 123;

  const auto rejects_atomically = [&](gjxl::SimpleAcMetadataInput input,
                                      std::string_view name) {
    const gjxl::Status rejected =
      gjxl::TokenizeSimpleAcMetadata(input, &tokens, &anchors);
    if (rejected.code() != gjxl::StatusCode::kInvalidArgument
        || tokens != sentinel || anchors != 123) {
      std::cerr << name << " rejection was not atomic\n";
      return false;
    }
    return true;
  };

  if (!rejects_atomically(
        OneBlockMetadataInput(&crossing, map, quant, sharpness, 1),
        "cross-group strategy")
      || !rejects_atomically(
        OneBlockMetadataInput(&unsupported, map, quant, sharpness),
        "unsupported strategy")) {
    return false;
  }

  gjxl::SimpleAcMetadataInput malformed =
    OneBlockMetadataInput(&dct8, map, quant, sharpness);
  malformed.y_to_x_map = {};
  const std::vector<int32_t> invalid_quant = {257};
  const std::vector<uint8_t> invalid_sharpness = {8};
  if (!rejects_atomically(malformed, "malformed CfL view")
      || !rejects_atomically(
        OneBlockMetadataInput(&dct8, map, invalid_quant, sharpness),
        "out-of-range quant")
      || !rejects_atomically(
        OneBlockMetadataInput(&dct8, map, quant, invalid_sharpness),
        "out-of-range sharpness")) {
    return false;
  }

  const std::array<std::vector<int32_t>, 3> oversized{{
    std::vector<int32_t>(257),
    std::vector<int32_t>(257),
    std::vector<int32_t>(257),
  }};
  const gjxl::Status status =
    gjxl::TokenizeSimpleDcGroup(DcView(oversized, {257, 1}), &tokens);
  if (status.code() != gjxl::StatusCode::kInvalidArgument
      || tokens != sentinel) {
    std::cerr << "Oversized group rejection was not atomic\n";
    return false;
  }
  return true;
}

struct ImageStorage {
  explicit ImageStorage(gjxl::Extent2D extent) : extent(extent) {
    for (std::vector<float>& values : plane) {
      values.resize(extent.width * extent.height);
    }
  }

  gjxl::ConstImage3FView ConstView() const {
    return gjxl::ConstImage3FView{{
      gjxl::ConstPlaneF32View{plane[0].data(), extent, extent.width},
      gjxl::ConstPlaneF32View{plane[1].data(), extent, extent.width},
      gjxl::ConstPlaneF32View{plane[2].data(), extent, extent.width},
    }};
  }

  gjxl::Extent2D extent;
  std::array<std::vector<float>, 3> plane;
};

gjxl::Status MakeFrame(size_t width,
                       gjxl::SimpleVarDctCodestreamProfile profile,
                       gjxl::VarDctEncoderFrame* frame) {
  gjxl::FrameGeometry geometry;
  gjxl::Status status = gjxl::FrameGeometry::Create(width, 1, &geometry);
  if (!status.ok()) {
    return status;
  }
  ImageStorage opsin(geometry.padded_frame());
  for (size_t x = 0; x < opsin.extent.width; ++x) {
    const float base = static_cast<float>((x * 17 + 5) % 101) * 0.002f;
    for (size_t y = 0; y < opsin.extent.height; ++y) {
      const size_t index = y * opsin.extent.width + x;
      opsin.plane[0][index] = base - 0.01f;
      opsin.plane[1][index] = base + static_cast<float>(y) * 0.003f;
      opsin.plane[2][index] = 1.2f * base + 0.02f;
    }
  }

  const gjxl::Extent2D blocks = geometry.block_grid().blocks;
  size_t block_count = 0;
  if (!blocks.try_area(&block_count)) {
    return gjxl::Status::InvalidArgument("Test block count overflow");
  }
  gjxl::AcStrategyGrid strategies;
  gjxl::Quantizer quantizer;
  gjxl::ColorCorrelationMap color_correlation;
  if (!(status = gjxl::AcStrategyGrid::Create(blocks, &strategies)).ok()) {
    return status;
  }
  strategies.fill_dct8();
  if (!(status = gjxl::Quantizer::Create({3541, 10}, &quantizer)).ok()) {
    return status;
  }
  if (!(status = gjxl::ComputeInitialColorCorrelationMap(opsin.ConstView(),
                                                         &color_correlation))
         .ok()) {
    return status;
  }
  const std::vector<int32_t> quant(block_count, 29);
  std::vector<uint8_t> sharpness(block_count);
  for (size_t index = 0; index < block_count; ++index) {
    sharpness[index] = static_cast<uint8_t>(index % 8);
  }
  return gjxl::ComputeQuantizedCoefficients(
    opsin.ConstView(),
    {
      .geometry = geometry,
      .strategies = &strategies,
      .raw_quant_field = View(quant, blocks),
      .quantizer = &quantizer,
      .color_correlation = &color_correlation,
      .epf_sharpness = View(sharpness, blocks),
    },
    profile, frame);
}

bool CheckFrameDimension(size_t width, size_t expected_blocks) {
  gjxl::VarDctEncoderFrame frame;
  gjxl::Status status = MakeFrame(width, {}, &frame);
  std::vector<gjxl::SimpleDcGroupTokenStreams> groups;
  if (status.ok()) {
    status = gjxl::TokenizeSimpleDcGroups(frame, &groups);
  }
  const size_t expected_groups =
    (expected_blocks + gjxl::kSimpleDcGroupBlockDimension - 1)
    / gjxl::kSimpleDcGroupBlockDimension;
  if (!status.ok() || groups.size() != expected_groups) {
    std::cerr << "Dimension " << width << " failed: " << status.message()
              << '\n';
    return false;
  }
  for (size_t index = 0; index < groups.size(); ++index) {
    const size_t origin = index * gjxl::kSimpleDcGroupBlockDimension;
    const size_t local_blocks =
      std::min(gjxl::kSimpleDcGroupBlockDimension, expected_blocks - origin);
    const size_t map_count = (local_blocks + 7) / 8;
    if (groups[index].block_x != origin || groups[index].block_y != 0
        || groups[index].block_extent != gjxl::Extent2D{local_blocks, 1}
        || groups[index].transform_anchor_count != local_blocks
        || groups[index].dc_tokens.size() != 3 * local_blocks
        || groups[index].ac_metadata_tokens.size()
             != 2 * map_count + 3 * local_blocks) {
      std::cerr << "Dimension " << width << " group layout is wrong\n";
      return false;
    }
  }

  if (expected_groups == 2) {
    const int32_t first_y = frame.quantized_dc().plane[1].Row(0)[256];
    const gjxl::EntropyToken expected_dc{
      26,
      gjxl::PackSigned(first_y),
    };
    const gjxl::EntropyToken expected_x_cfl{
      2,
      gjxl::PackSigned(frame.color_correlation().y_to_x_map().Row(0)[32]),
    };
    const gjxl::EntropyToken expected_b_cfl{
      1,
      gjxl::PackSigned(frame.color_correlation().y_to_b_map().Row(0)[32]),
    };
    if (groups[1].dc_tokens.front() != expected_dc
        || groups[1].ac_metadata_tokens[0] != expected_x_cfl
        || groups[1].ac_metadata_tokens[1] != expected_b_cfl) {
      std::cerr
        << "The second DC group did not reset or slice its predictors\n";
      return false;
    }
  }
  return true;
}

bool CheckDimensionsAndFrameAtomicity() {
  if (!CheckFrameDimension(1, 1) || !CheckFrameDimension(8, 1)
      || !CheckFrameDimension(9, 2) || !CheckFrameDimension(2048, 256)
      || !CheckFrameDimension(2049, 257)) {
    return false;
  }

  gjxl::SimpleVarDctCodestreamProfile profile;
  profile.quantization_matrix_mode =
    gjxl::QuantizationMatrixMode::kCustom;
  gjxl::VarDctEncoderFrame invalid_profile;
  gjxl::Status status = MakeFrame(8, profile, &invalid_profile);
  std::vector<gjxl::SimpleDcGroupTokenStreams> groups(1);
  groups[0].block_x = 999;
  if (!status.ok()) {
    return false;
  }
  status = gjxl::TokenizeSimpleDcGroups(invalid_profile, &groups);
  if (status.code() != gjxl::StatusCode::kInvalidArgument || groups.size() != 1
      || groups[0].block_x != 999) {
    std::cerr << "Rejected frame changed the group-token output\n";
    return false;
  }
  return true;
}

template <size_t Size>
bool HasBytes(const gjxl::BitWriter& writer,
              const std::array<uint8_t, Size>& expected) {
  return std::ranges::equal(writer.padded_bytes(), expected);
}

bool CheckModularHeaders() {
  gjxl::BitWriter dc;
  gjxl::BitWriter one;
  gjxl::BitWriter partial;
  gjxl::BitWriter maximum;
  if (!gjxl::WriteSimpleDcGroupModularHeader(&dc).ok() || dc.bits_written() != 6
      || !HasBytes(dc, std::array<uint8_t, 1>{0x0c})
      || !gjxl::WriteSimpleAcMetadataModularHeader({1, 1}, 1, &one).ok()
      || one.bits_written() != 4 || !HasBytes(one, std::array<uint8_t, 1>{0x03})
      || !gjxl::WriteSimpleAcMetadataModularHeader({3, 2}, 4, &partial).ok()
      || partial.bits_written() != 7
      || !HasBytes(partial, std::array<uint8_t, 1>{0x1b})
      || !gjxl::WriteSimpleAcMetadataModularHeader({256, 256}, 65536, &maximum)
            .ok()
      || maximum.bits_written() != 20
      || !HasBytes(maximum, std::array<uint8_t, 3>{0xff, 0xff, 0x03})) {
    std::cerr << "Modular-header byte fixture failed\n";
    return false;
  }

  gjxl::BitWriter atomic;
  if (!atomic.WriteBits(3, 5).ok()) {
    return false;
  }
  const gjxl::Status status =
    gjxl::WriteSimpleAcMetadataModularHeader({3, 2}, 0, &atomic);
  if (status.code() != gjxl::StatusCode::kInvalidArgument
      || atomic.bits_written() != 3
      || !HasBytes(atomic, std::array<uint8_t, 1>{0x05})) {
    std::cerr << "Invalid modular header changed its writer\n";
    return false;
  }
  return true;
}

}  // namespace

int main() {
  if (!CheckPinnedTinyFixture() || !CheckDcSignedExtremesAndAtomicOverflow()
      || !CheckAllStrategiesAndActualMetadata()
      || !CheckMetadataRejectionsAreAtomic()
      || !CheckDimensionsAndFrameAtomicity() || !CheckModularHeaders()) {
    return EXIT_FAILURE;
  }
  std::cout << "All DC-group tokenization tests passed.\n";
  return EXIT_SUCCESS;
}
