// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Yunho Cho

/// @file
/// Validates the CPU quantization foundation against pinned libjxl output.

#include <array>
#include <bit>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <span>
#include <string_view>
#include <vector>

#include "codec/quantization.h"

namespace {

using gjxl::AcStrategyType;
using gjxl::XybChannel;

constexpr std::string_view kPinnedLibjxlRevision =
  "e8ff09762481785938d8e4e01333ed3917571161";

uint32_t FloatBits(float value) {
  return std::bit_cast<uint32_t>(value);
}

uint64_t HashQuantized(std::span<const int32_t> values) {
  uint64_t hash = 1469598103934665603ull;
  for (const int32_t value : values) {
    hash ^= static_cast<uint32_t>(value);
    hash *= 1099511628211ull;
  }
  return hash;
}

uint64_t HashFloats(std::span<const float> values) {
  uint64_t hash = 1469598103934665603ull;
  for (const float value : values) {
    hash ^= FloatBits(value);
    hash *= 1099511628211ull;
  }
  return hash;
}

struct MatrixHashGolden {
  AcStrategyType strategy;
  XybChannel channel;
  uint64_t dequant_hash;
  uint64_t inverse_dequant_hash;
};

// Generated by constructing DequantMatrices from the pinned libjxl revision.
// Hashes cover every coefficient of every built-in DCT table family and XYB
// channel, including the low-frequency inverse-table exclusion.
constexpr std::array kMatrixHashGoldens = {
  MatrixHashGolden{
    AcStrategyType::kDct8, XybChannel::kX,
    0xc490cc1bbe1973f5ull, 0xd23520a7b9c22353ull},
  MatrixHashGolden{
    AcStrategyType::kDct8, XybChannel::kY,
    0xb3b8673872c6cd8dull, 0xbbd9690dd3b059a6ull},
  MatrixHashGolden{
    AcStrategyType::kDct8, XybChannel::kB,
    0x7c6d8b44ff713bf5ull, 0xfe138a0f5962cd9dull},
  MatrixHashGolden{
    AcStrategyType::kDct16x16, XybChannel::kX,
    0x55bde522670a7908ull, 0xebb8fdedb665c3a6ull},
  MatrixHashGolden{
    AcStrategyType::kDct16x16, XybChannel::kY,
    0xc8d3604b4fb052fbull, 0xbadb1d45a19d54e2ull},
  MatrixHashGolden{
    AcStrategyType::kDct16x16, XybChannel::kB,
    0x5254bb7bb00437caull, 0xa659e416b8a87210ull},
  MatrixHashGolden{
    AcStrategyType::kDct32x32, XybChannel::kX,
    0xd851bd773699442full, 0xd938123e62470afeull},
  MatrixHashGolden{
    AcStrategyType::kDct32x32, XybChannel::kY,
    0x25590c8ad99bb000ull, 0x2fd739043d5e9a32ull},
  MatrixHashGolden{
    AcStrategyType::kDct32x32, XybChannel::kB,
    0x2ee2424dd4dc5ff6ull, 0x2a8b2d9027266793ull},
  MatrixHashGolden{
    AcStrategyType::kDct8x16, XybChannel::kX,
    0x90747bb7cb7752b3ull, 0xe0d8b42d0d5dfe35ull},
  MatrixHashGolden{
    AcStrategyType::kDct8x16, XybChannel::kY,
    0xfc5ecfe472d00388ull, 0xf8e506ff8a0d86d1ull},
  MatrixHashGolden{
    AcStrategyType::kDct8x16, XybChannel::kB,
    0x6db0933844e2a2e5ull, 0x13beb04403fdc62bull},
  MatrixHashGolden{
    AcStrategyType::kDct16x32, XybChannel::kX,
    0x84781ba6e89cc800ull, 0xecd4bef6f4e07dedull},
  MatrixHashGolden{
    AcStrategyType::kDct16x32, XybChannel::kY,
    0x64b2dfae01ef7e1cull, 0x4c87bcd2c0f2fde2ull},
  MatrixHashGolden{
    AcStrategyType::kDct16x32, XybChannel::kB,
    0x723189fc9399aeabull, 0x9d54e6949187b57cull},
};

struct StrategyMatrixCase {
  AcStrategyType strategy;
  gjxl::Extent2D extent;
  gjxl::Extent2D low_frequency_extent;
};

constexpr std::array kStrategyMatrixCases = {
  StrategyMatrixCase{AcStrategyType::kDct8, {8, 8}, {1, 1}},
  StrategyMatrixCase{AcStrategyType::kDct16x16, {16, 16}, {2, 2}},
  StrategyMatrixCase{AcStrategyType::kDct32x32, {32, 32}, {4, 4}},
  StrategyMatrixCase{AcStrategyType::kDct16x8, {16, 8}, {2, 1}},
  StrategyMatrixCase{AcStrategyType::kDct8x16, {16, 8}, {2, 1}},
  StrategyMatrixCase{AcStrategyType::kDct32x16, {32, 16}, {4, 2}},
  StrategyMatrixCase{AcStrategyType::kDct16x32, {32, 16}, {4, 2}},
};

bool CheckDefaultMatrices() {
  constexpr std::array channels = {
    XybChannel::kX,
    XybChannel::kY,
    XybChannel::kB,
  };

  for (const StrategyMatrixCase& test : kStrategyMatrixCases) {
    for (const XybChannel channel : channels) {
      gjxl::QuantizationMatrixView matrix;
      const gjxl::Status status = gjxl::GetDefaultQuantizationMatrix(
        test.strategy,
        channel,
        &matrix);

      const size_t count = test.extent.width * test.extent.height;
      if (!status.ok() ||
          matrix.coefficient_extent != test.extent ||
          matrix.low_frequency_extent != test.low_frequency_extent ||
          matrix.dequant.size() != count ||
          matrix.inverse_dequant.size() != count) {

        std::cerr << "Quantization matrix geometry is incorrect\n";
        return false;
      }

      for (size_t y = 0; y < test.extent.height; ++y) {
        for (size_t x = 0; x < test.extent.width; ++x) {
          const size_t index = y * test.extent.width + x;
          const bool is_low_frequency =
            x < test.low_frequency_extent.width &&
            y < test.low_frequency_extent.height;

          if (!(matrix.dequant[index] > 0.0f) ||
              (is_low_frequency && matrix.inverse_dequant[index] != 0.0f) ||
              (!is_low_frequency &&
               std::abs(
                 matrix.dequant[index] * matrix.inverse_dequant[index] -
                 1.0f) > 2.0e-7f)) {

            std::cerr << "Quantization matrix contents are invalid\n";
            return false;
          }
        }
      }
    }
  }

  for (const MatrixHashGolden& golden : kMatrixHashGoldens) {
    gjxl::QuantizationMatrixView matrix;
    const gjxl::Status status = gjxl::GetDefaultQuantizationMatrix(
      golden.strategy,
      golden.channel,
      &matrix);

    if (!status.ok() ||
        HashFloats(matrix.dequant) != golden.dequant_hash ||
        HashFloats(matrix.inverse_dequant) != golden.inverse_dequant_hash) {

      std::cerr
        << "Default matrix differs from libjxl "
        << kPinnedLibjxlRevision
        << '\n';
      return false;
    }
  }

  gjxl::QuantizationMatrixView dct16x8;
  gjxl::QuantizationMatrixView dct8x16;
  gjxl::QuantizationMatrixView dct32x16;
  gjxl::QuantizationMatrixView dct16x32;

  if (!gjxl::GetDefaultQuantizationMatrix(
        AcStrategyType::kDct16x8,
        XybChannel::kY,
        &dct16x8).ok() ||
      !gjxl::GetDefaultQuantizationMatrix(
        AcStrategyType::kDct8x16,
        XybChannel::kY,
        &dct8x16).ok() ||
      !gjxl::GetDefaultQuantizationMatrix(
        AcStrategyType::kDct32x16,
        XybChannel::kY,
        &dct32x16).ok() ||
      !gjxl::GetDefaultQuantizationMatrix(
        AcStrategyType::kDct16x32,
        XybChannel::kY,
        &dct16x32).ok() ||
      dct16x8.dequant.data() != dct8x16.dequant.data() ||
      dct16x8.inverse_dequant.data() != dct8x16.inverse_dequant.data() ||
      dct32x16.dequant.data() != dct16x32.dequant.data() ||
      dct32x16.inverse_dequant.data() != dct16x32.inverse_dequant.data()) {

    std::cerr << "Transpose strategies do not share canonical matrices\n";
    return false;
  }

  gjxl::QuantizationMatrixView unused;
  if (gjxl::GetDefaultQuantizationMatrix(
        AcStrategyType::kIdentity,
        XybChannel::kY,
        &unused).ok() ||
      gjxl::GetDefaultQuantizationMatrix(
        AcStrategyType::kDct8,
        static_cast<XybChannel>(255),
        &unused).ok() ||
      gjxl::GetDefaultQuantizationMatrix(
        AcStrategyType::kDct8,
        XybChannel::kY,
        nullptr).ok()) {

    std::cerr << "Invalid matrix request was accepted\n";
    return false;
  }

  return true;
}

constexpr std::array<float, 12> kQuantField = {
  0.75f, 1.25f, 2.0f, 3.5f,
  4.0f, 5.25f, 6.5f, 8.0f,
  9.5f, 12.0f, 16.0f, 21.0f,
};

void StoreQuantField(std::array<float, 18>* storage) {
  storage->fill(-1.0f);
  for (size_t y = 0; y < 3; ++y) {
    for (size_t x = 0; x < 4; ++x) {
      (*storage)[y * 6 + x] = kQuantField[y * 4 + x];
    }
  }
}

bool CheckRawField(
  const std::array<int32_t, 18>& storage,
  std::span<const int32_t, 12> expected) {

  for (size_t y = 0; y < 3; ++y) {
    for (size_t x = 0; x < 4; ++x) {
      if (storage[y * 6 + x] != expected[y * 4 + x]) {
        return false;
      }
    }
    if (storage[y * 6 + 4] != -777 || storage[y * 6 + 5] != -777) {
      return false;
    }
  }
  return true;
}

bool CheckQuantizerAndFields() {
  gjxl::Quantizer direct;
  if (!gjxl::Quantizer::Create({1024, 64}, &direct).ok() ||
      !direct.valid() ||
      direct.scale() != 0.015625f ||
      direct.inverse_global_scale() != 64.0f ||
      direct.dc_steps() !=
        std::array<float, 3>{1.0f / 4096.0f, 1.0f / 512.0f, 1.0f / 256.0f} ||
      direct.inverse_dc_steps() !=
        std::array<float, 3>{4096.0f, 512.0f, 256.0f}) {

    std::cerr << "Direct quantizer construction is incorrect\n";
    return false;
  }

  gjxl::Quantizer unused;
  if (gjxl::Quantizer::Create({0, 64}, &unused).ok() ||
      gjxl::Quantizer::Create({32769, 64}, &unused).ok() ||
      gjxl::Quantizer::Create({1024, 0}, &unused).ok() ||
      gjxl::Quantizer::Create({1024, 65537}, &unused).ok() ||
      gjxl::Quantizer::Create({1024, 64}, nullptr).ok()) {

    std::cerr << "Invalid quantizer parameters were accepted\n";
    return false;
  }

  std::array<int32_t, 18> raw_storage;
  raw_storage.fill(-777);
  const gjxl::PlaneI32View raw{
    .data = raw_storage.data(),
    .extent = {4, 3},
    .stride = 6,
  };

  gjxl::Quantizer uniform;
  if (!gjxl::CreateUniformQuantizer(1.7f, 3.25f, raw, &uniform).ok() ||
      uniform.params().global_scale != 11141 ||
      uniform.params().quant_dc != 10) {

    std::cerr << "Uniform quantizer differs from pinned libjxl\n";
    return false;
  }

  constexpr std::array<int32_t, 12> kUniformRaw = {
    19, 19, 19, 19,
    19, 19, 19, 19,
    19, 19, 19, 19,
  };
  if (!CheckRawField(raw_storage, kUniformRaw)) {
    std::cerr << "Uniform raw quant field is incorrect\n";
    return false;
  }

  std::array<float, 18> field_storage;
  StoreQuantField(&field_storage);
  const gjxl::ConstPlaneF32View field{
    .data = field_storage.data(),
    .extent = {4, 3},
    .stride = 6,
  };

  raw_storage.fill(-777);
  gjxl::Quantizer adaptive;
  if (!gjxl::CreateQuantizerFromField(
        1.7f,
        field,
        raw,
        &adaptive).ok() ||
      adaptive.params().global_scale != 11141 ||
      adaptive.params().quant_dc != 10) {

    std::cerr << "Quant field conversion differs from pinned libjxl\n";
    return false;
  }

  constexpr std::array<int32_t, 12> kAdaptiveRaw = {
    4, 7, 12, 21,
    24, 31, 38, 47,
    56, 71, 94, 124,
  };
  if (!CheckRawField(raw_storage, kAdaptiveRaw)) {
    std::cerr << "Adaptive raw quant field is incorrect\n";
    return false;
  }

  raw_storage.fill(-777);
  if (!gjxl::CreateQuantizerFromField(
        20.0f,
        field,
        raw,
        &adaptive).ok() ||
      adaptive.params().global_scale != 26214 ||
      adaptive.params().quant_dc != 50) {

    std::cerr << "Uncapped quant field statistics are incorrect\n";
    return false;
  }

  constexpr std::array<int32_t, 12> kUncappedRaw = {
    2, 3, 5, 9,
    10, 13, 16, 20,
    24, 30, 40, 53,
  };
  if (!CheckRawField(raw_storage, kUncappedRaw)) {
    std::cerr << "Uncapped raw quant field is incorrect\n";
    return false;
  }

  field_storage[0] = 0.0f;
  if (gjxl::CreateQuantizerFromField(
        1.7f,
        field,
        raw,
        &unused).ok() ||
      gjxl::CreateUniformQuantizer(
        1.7f,
        std::numeric_limits<float>::infinity(),
        raw,
        &unused).ok()) {

    std::cerr << "Invalid quant field was accepted\n";
    return false;
  }

  return true;
}

struct BlockGolden {
  AcStrategyType strategy;
  std::array<uint64_t, 3> quantized_hash;
  std::array<uint64_t, 3> dequantized_hash;
};

// Full-block FNV-1a hashes from the pinned implementation's default matrices
// and fixed (non-AdjustQuantBlockAC) quantization path. The transpose pairs
// intentionally share hashes because coefficients use canonical layout.
constexpr std::array kBlockGoldens = {
  BlockGolden{
    AcStrategyType::kDct8,
    {0x4bb249537c3c2efaull, 0xa775b46201b662bfull, 0x30da554179aca361ull},
    {0xd90a0ff7345f7d97ull, 0x0df6fb714d735a10ull, 0x39363fd91ff950dfull}},
  BlockGolden{
    AcStrategyType::kDct16x16,
    {0x1d3b2db5123c5519ull, 0x841552357897b83dull, 0x9c4f39e17445704aull},
    {0xff350302b08c5fe8ull, 0xff4c5d532b02b8dbull, 0xcd190039006b2920ull}},
  BlockGolden{
    AcStrategyType::kDct32x32,
    {0x978a546c14b2a0dcull, 0x51614216f343f204ull, 0x1e2d493865d96aebull},
    {0xfb05303006ddd303ull, 0x9a734988d558ba16ull, 0x382ad087c45fd342ull}},
  BlockGolden{
    AcStrategyType::kDct16x8,
    {0xb3810944bd183afeull, 0x7e8a53bc4008e30full, 0x412085da7a9a0ee0ull},
    {0x59700e4343f85f23ull, 0xcbe879b07e7d10a8ull, 0xb84db3a66b327d3dull}},
  BlockGolden{
    AcStrategyType::kDct8x16,
    {0xb3810944bd183afeull, 0x7e8a53bc4008e30full, 0x412085da7a9a0ee0ull},
    {0x59700e4343f85f23ull, 0xcbe879b07e7d10a8ull, 0xb84db3a66b327d3dull}},
  BlockGolden{
    AcStrategyType::kDct32x16,
    {0xa8aaf3c0c1b2848cull, 0xbdba30c29d209e07ull, 0x957193847b2bd3fbull},
    {0xa1f454ddf42576aaull, 0x65cc30fcb287ba57ull, 0x69e3bdcdb7976b1bull}},
  BlockGolden{
    AcStrategyType::kDct16x32,
    {0xa8aaf3c0c1b2848cull, 0xbdba30c29d209e07ull, 0x957193847b2bd3fbull},
    {0xa1f454ddf42576aaull, 0x65cc30fcb287ba57ull, 0x69e3bdcdb7976b1bull}},
};

bool MakeBlockQuantizer(gjxl::Quantizer* quantizer, int32_t* raw_quant) {
  std::array<float, 18> field_storage;
  StoreQuantField(&field_storage);
  std::array<int32_t, 18> raw_storage{};

  const gjxl::Status status = gjxl::CreateQuantizerFromField(
    1.7f,
    {
      .data = field_storage.data(),
      .extent = {4, 3},
      .stride = 6,
    },
    {
      .data = raw_storage.data(),
      .extent = {4, 3},
      .stride = 6,
    },
    quantizer);

  if (!status.ok()) {
    return false;
  }

  *raw_quant = raw_storage[1 * 6 + 2];
  return true;
}

bool CheckAcBlocks() {
  gjxl::Quantizer quantizer;
  int32_t raw_quant = 0;
  if (!MakeBlockQuantizer(&quantizer, &raw_quant) || raw_quant != 38) {
    std::cerr << "Failed to prepare block quantizer\n";
    return false;
  }

  constexpr std::array channels = {
    XybChannel::kX,
    XybChannel::kY,
    XybChannel::kB,
  };
  constexpr std::array multipliers = {0.82f, 1.0f, 0.73f};

  for (const BlockGolden& golden : kBlockGoldens) {
    const gjxl::AcStrategyInfo* info = gjxl::GetAcStrategyInfo(golden.strategy);
    if (info == nullptr) {
      std::cerr << "Missing block strategy metadata\n";
      return false;
    }

    const size_t count = info->coefficient_count();
    std::vector<float> coefficients(count);
    for (size_t index = 0; index < count; ++index) {
      coefficients[index] =
        static_cast<float>(
          static_cast<int32_t>((index * 37) % 101) - 50) *
        0.000137f;
    }

    for (size_t channel = 0; channel < channels.size(); ++channel) {
      std::vector<int32_t> quantized(count);
      const gjxl::AcQuantizationOptions options{
        .channel = channels[channel],
        .matrix_multiplier = multipliers[channel],
      };

      const gjxl::Status quantize_status = gjxl::QuantizeAcBlock(
        golden.strategy,
        quantizer,
        raw_quant,
        options,
        coefficients,
        quantized);

      if (!quantize_status.ok() ||
          HashQuantized(quantized) != golden.quantized_hash[channel]) {

        std::cerr
          << "Quantized block differs from pinned libjxl for strategy "
          << static_cast<unsigned int>(golden.strategy)
          << " channel "
          << channel
          << '\n';
        return false;
      }

      std::vector<float> dequantized(count);
      const gjxl::Status dequantize_status = gjxl::DequantizeAcBlock(
        golden.strategy,
        quantizer,
        raw_quant,
        options,
        quantized,
        dequantized);

      if (!dequantize_status.ok() ||
          HashFloats(dequantized) != golden.dequantized_hash[channel]) {

        std::cerr
          << "Dequantized block differs from pinned scalar output for strategy "
          << static_cast<unsigned int>(golden.strategy)
          << " channel "
          << channel
          << '\n';
        return false;
      }

      gjxl::QuantizationMatrixView matrix;
      if (!gjxl::GetDefaultQuantizationMatrix(
            golden.strategy,
            channels[channel],
            &matrix).ok()) {
        return false;
      }

      for (size_t y = 0; y < matrix.low_frequency_extent.height; ++y) {
        for (size_t x = 0; x < matrix.low_frequency_extent.width; ++x) {
          if (quantized[y * matrix.coefficient_extent.width + x] != 0) {
            std::cerr << "AC quantization emitted a low-frequency value\n";
            return false;
          }
        }
      }
    }
  }

  std::array<float, 64> coefficients{};
  std::array<int32_t, 64> quantized{};
  std::array<float, 64> dequantized{};
  gjxl::Quantizer invalid_quantizer;

  if (gjxl::QuantizeAcBlock(
        AcStrategyType::kDct8,
        invalid_quantizer,
        raw_quant,
        {},
        coefficients,
        quantized).ok() ||
      gjxl::QuantizeAcBlock(
        AcStrategyType::kDct8,
        quantizer,
        0,
        {},
        coefficients,
        quantized).ok() ||
      gjxl::QuantizeAcBlock(
        AcStrategyType::kIdentity,
        quantizer,
        raw_quant,
        {},
        coefficients,
        quantized).ok() ||
      gjxl::QuantizeAcBlock(
        AcStrategyType::kDct8,
        quantizer,
        raw_quant,
        {.channel = XybChannel::kY, .matrix_multiplier = 0.0f},
        coefficients,
        quantized).ok() ||
      gjxl::DequantizeAcBlock(
        AcStrategyType::kDct8,
        quantizer,
        raw_quant,
        {},
        std::span<const int32_t>(quantized).first(63),
        dequantized).ok()) {

    std::cerr << "Invalid AC operation was accepted\n";
    return false;
  }

  coefficients[7] = std::numeric_limits<float>::infinity();
  if (gjxl::QuantizeAcBlock(
        AcStrategyType::kDct8,
        quantizer,
        raw_quant,
        {},
        coefficients,
        quantized).ok()) {

    std::cerr << "Non-finite AC coefficient was accepted\n";
    return false;
  }

  return true;
}

}  // namespace

int main() {
  if (!CheckDefaultMatrices() ||
      !CheckQuantizerAndFields() ||
      !CheckAcBlocks()) {

    return EXIT_FAILURE;
  }

  std::cout << "All quantization tests passed.\n";
  return EXIT_SUCCESS;
}
