#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Yunho Cho

"""Generate float32 orthonormal DCT-II basis tables for Metal.

By default, this writes the 8-, 16-, and 32-point tables to
``src/gpu/metal/kernels/dct_basis.h``. Use ``--check`` to verify
that an existing generated file is current without modifying it.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
import struct
import sys
from typing import Sequence


DEFAULT_SIZES = (8, 16, 32)
REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = (
    REPOSITORY_ROOT
    / "src"
    / "gpu"
    / "metal"
    / "kernels"
    / "dct_basis.h"
)


def to_float32(value: float) -> float:
    """Rounds a Python double to IEEE-754 binary32."""

    return struct.unpack("<f", struct.pack("<f", value))[0]


def float32_bits(value: float) -> bytes:
    """Returns the IEEE-754 binary32 representation of ``value``."""

    return struct.pack("<f", value)


def make_orthonormal_dct2_basis(size: int) -> list[float]:
    """Returns a row-major ``[frequency][sample]`` DCT-II basis."""

    scale = math.sqrt(2.0 / size)
    basis: list[float] = []

    for frequency in range(size):
        alpha = 1.0 / math.sqrt(2.0) if frequency == 0 else 1.0

        for sample in range(size):
            angle = (
                (sample + 0.5)
                * frequency
                * math.pi
                / size
            )
            value = alpha * scale * math.cos(angle)
            basis.append(to_float32(value))

    return basis


def validate_basis(size: int, basis: Sequence[float]) -> None:
    """Checks dimensions, finiteness, DC normalization, and orthonormality."""

    if len(basis) != size * size:
        raise ValueError(
            f"DCT{size} basis has {len(basis)} values; expected {size * size}"
        )

    if not all(math.isfinite(value) for value in basis):
        raise ValueError(f"DCT{size} basis contains a non-finite value")

    expected_dc = to_float32(1.0 / math.sqrt(size))
    for sample in range(size):
        if float32_bits(basis[sample]) != float32_bits(expected_dc):
            raise ValueError(
                f"DCT{size} DC basis value {sample} is not 1/sqrt({size})"
            )

    max_error = 0.0
    for lhs_frequency in range(size):
        lhs_offset = lhs_frequency * size

        for rhs_frequency in range(size):
            rhs_offset = rhs_frequency * size
            dot_product = math.fsum(
                basis[lhs_offset + sample]
                * basis[rhs_offset + sample]
                for sample in range(size)
            )
            expected = 1.0 if lhs_frequency == rhs_frequency else 0.0
            max_error = max(max_error, abs(dot_product - expected))

    if max_error > 2.0e-6:
        raise ValueError(
            f"DCT{size} float32 basis is not orthonormal; "
            f"maximum error is {max_error:.9g}"
        )


def format_float32(value: float) -> str:
    """Formats a binary32 value as a round-trippable Metal float literal."""

    text = format(value, ".9g")

    if "." not in text and "e" not in text:
        text += ".0"

    if float32_bits(float(text)) != float32_bits(value):
        raise ValueError(f"float literal does not round-trip to binary32: {text}")

    return text + "f"


def render_basis(size: int, basis: Sequence[float]) -> list[str]:
    """Renders one Metal constant array."""

    lines = [
        f"constant float kOrthonormalDct{size}[{size * size}] = {{",
    ]

    values_per_line = 8
    for frequency in range(size):
        lines.append(f"  // Frequency {frequency}")
        row_offset = frequency * size

        for first_sample in range(0, size, values_per_line):
            last_sample = min(first_sample + values_per_line, size)
            literals = ", ".join(
                format_float32(basis[row_offset + sample])
                for sample in range(first_sample, last_sample)
            )
            lines.append(f"  {literals},")

    lines.append("};")
    return lines


def render_file(sizes: Sequence[int]) -> str:
    """Renders the complete generated Metal include."""

    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Copyright (c) 2026 Yunho Cho",
        "//",
        "// Generated by scripts/generate_dct_basis.py. Do not edit.",
        "// Tables are row-major [frequency][sample] orthonormal DCT-II bases.",
        "",
        "#pragma once",
        "",
    ]

    for index, size in enumerate(sizes):
        basis = make_orthonormal_dct2_basis(size)
        validate_basis(size, basis)
        lines.extend(render_basis(size, basis))

        if index + 1 != len(sizes):
            lines.append("")

    lines.append("")
    return "\n".join(lines)


def validate_sizes(sizes: Sequence[int]) -> tuple[int, ...]:
    """Validates and canonicalizes requested transform lengths."""

    if not sizes:
        raise ValueError("at least one DCT size is required")

    unique_sizes = tuple(sorted(set(sizes)))
    for size in unique_sizes:
        if size <= 0 or size & (size - 1):
            raise ValueError(
                f"DCT size must be a positive power of two, got {size}"
            )

    return unique_sizes


def write_file(path: Path, contents: str) -> None:
    """Writes ``contents`` to ``path``."""

    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open(mode="w", encoding="utf-8", newline="\n") as output_file:
        output_file.write(contents)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sizes",
        metavar="N",
        type=int,
        nargs="+",
        default=DEFAULT_SIZES,
        help="power-of-two basis lengths to generate (default: 8 16 32)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"generated Metal include (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the output is missing or differs; do not write it",
    )
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()

    try:
        sizes = validate_sizes(arguments.sizes)
        contents = render_file(sizes)
    except (OverflowError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    output = arguments.output.resolve()

    if arguments.check:
        try:
            existing_contents = output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"error: generated file is missing: {output}", file=sys.stderr)
            return 1

        if existing_contents != contents:
            print(f"error: generated file is stale: {output}", file=sys.stderr)
            return 1

        print(f"DCT basis tables are current: {output}")
        return 0

    write_file(output, contents)
    print(f"Generated DCT basis tables: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
