// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Yunho Cho

#include <array>
#include <bit>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <iomanip>
#include <iostream>
#include <string_view>
#include <vector>

#include "butteraugli_fixtures.h"
#include "butteraugli_oracle.h"

namespace {

using gjxl::butteraugli_test::FixtureKind;
using gjxl::butteraugli_test::FixtureSpec;
using gjxl::butteraugli_test::IntermediateStageOutput;
using gjxl::butteraugli_test::OraclePlane;

constexpr std::string_view kPinnedLibjxlRevision =
    "e8ff09762481785938d8e4e01333ed3917571161";
constexpr size_t kFullWidth = 32;
constexpr size_t kFullHeight = 24;
constexpr size_t kIntermediateWidth = 16;
constexpr size_t kIntermediateHeight = 12;

void PrintUint32Array(const std::vector<float> &values, size_t indent) {
  const std::string padding(indent, ' ');
  for (size_t index = 0; index < values.size(); ++index) {
    if (index % 8 == 0) {
      std::cout << padding;
    }
    std::cout << "0x" << std::hex << std::setw(8) << std::setfill('0')
              << std::bit_cast<uint32_t>(values[index]) << "u";
    if (index + 1 != values.size()) {
      std::cout << ',';
      if (index % 8 != 7) {
        std::cout << ' ';
      }
    }
    if (index % 8 == 7 || index + 1 == values.size()) {
      std::cout << '\n';
    }
  }
  std::cout << std::dec << std::setfill(' ');
}

[[nodiscard]] bool GenerateFullMap(FixtureKind kind, std::vector<float> *map,
                                   double *score) {
  const auto fixture = gjxl::butteraugli_test::MakeFixture({
      "golden",
      {kFullWidth, kFullHeight},
      kind,
  });
  map->assign(kFullWidth * kFullHeight, -1.0f);
  return gjxl::butteraugli_test::ComputeLiveButteraugli(
      fixture.reference.ConstView(), fixture.distorted.ConstView(),
      fixture.options,
      OraclePlane{map->data(), {kFullWidth, kFullHeight}, kFullWidth}, score);
}

} // namespace

int main() {
  const std::array<FixtureKind, 4> kinds = {
      FixtureKind::kFlat,
      FixtureKind::kTexture,
      FixtureKind::kContrast,
      FixtureKind::kChromatic,
  };
  std::array<std::vector<float>, 4> maps;
  std::array<double, 4> scores{};
  for (size_t index = 0; index < kinds.size(); ++index) {
    if (!GenerateFullMap(kinds[index], &maps[index], &scores[index])) {
      std::cerr << "Unable to generate scalar Butteraugli full-map golden\n";
      return EXIT_FAILURE;
    }
  }

  const auto stage_fixture = gjxl::butteraugli_test::MakeFixture({
      "intermediate",
      {kIntermediateWidth, kIntermediateHeight},
      FixtureKind::kIntermediate,
  });
  IntermediateStageOutput stages;
  if (!gjxl::butteraugli_test::ComputePinnedIntermediateStages(
          stage_fixture.reference.ConstView(),
          stage_fixture.distorted.ConstView(), stage_fixture.options,
          &stages)) {
    std::cerr << "Unable to generate scalar Butteraugli stage goldens\n";
    return EXIT_FAILURE;
  }

  std::cout
      << "// SPDX-License-Identifier: Apache-2.0\n"
      << "// Copyright (c) 2026 Yunho Cho\n\n"
      << "// Generated by tools/generate_butteraugli_goldens.cpp from libjxl\n"
      << "// " << kPinnedLibjxlRevision << ". Do not edit manually.\n\n"
      << "#pragma once\n\n"
      << "#include <array>\n"
      << "#include <cstddef>\n"
      << "#include <cstdint>\n\n"
      << "namespace gjxl::butteraugli_test::golden {\n\n"
      << "inline constexpr size_t kFullMapWidth = " << kFullWidth << ";\n"
      << "inline constexpr size_t kFullMapHeight = " << kFullHeight << ";\n"
      << "inline constexpr size_t kFullMapArea =\n"
      << "  kFullMapWidth * kFullMapHeight;\n"
      << "inline constexpr size_t kFullMapCount = 4;\n\n"
      << "inline constexpr std::array<std::array<uint32_t, kFullMapArea>,\n"
      << "                            kFullMapCount> kFullMapBits = {{\n";
  for (const std::vector<float> &map : maps) {
    std::cout << "  {{\n";
    PrintUint32Array(map, 4);
    std::cout << "  }},\n";
  }
  std::cout << "}};\n\n"
            << "inline constexpr std::array<uint64_t, kFullMapCount>\n"
            << "  kFullMapScoreBits = {\n  ";
  for (size_t index = 0; index < scores.size(); ++index) {
    std::cout << "0x" << std::hex << std::setw(16) << std::setfill('0')
              << std::bit_cast<uint64_t>(scores[index]) << "ull";
    if (index + 1 != scores.size()) {
      std::cout << ", ";
    }
  }
  std::cout << std::dec << std::setfill(' ') << "\n};\n\n"
            << "inline constexpr size_t kIntermediateWidth = "
            << kIntermediateWidth << ";\n"
            << "inline constexpr size_t kIntermediateHeight = "
            << kIntermediateHeight << ";\n"
            << "inline constexpr size_t kIntermediateArea =\n"
            << "  kIntermediateWidth * kIntermediateHeight;\n"
            << "inline constexpr size_t kIntermediateStageCount = "
            << gjxl::butteraugli_test::kIntermediateStageCount << ";\n\n"
            << "inline constexpr std::array<\n"
            << "  std::array<uint32_t, kIntermediateArea>,\n"
            << "  kIntermediateStageCount> kIntermediateStageBits = {{\n";
  for (const std::vector<float> &plane : stages.plane) {
    std::cout << "  {{\n";
    PrintUint32Array(plane, 4);
    std::cout << "  }},\n";
  }
  std::cout << "}};\n\n"
            << "}  // namespace gjxl::butteraugli_test::golden\n";
  return EXIT_SUCCESS;
}
