//! Raw bindings for GJXL's C interface.
//!
//! Bindings and native link directives are generated by the `native` feature.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

#[cfg(feature = "native")]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
